src/Entity/Evenement.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @Assert\GreaterThan("today")
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="blob")
     */
    private $image;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomimage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     * min=4,
     * max=50)
     */

    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $time;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurant::class, inversedBy="evenements")
     *
     */
    private $Restaurant;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Evenement")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }
    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }





    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(?\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function setRestaurant($Restaurant)
    {
        $this->Restaurant = $Restaurant;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->Restaurant;
    }
    /**
     * @return mixed
     */
    public function getNomimage()
    {
        return $this->nomimage;
    }

    /**
     * @param mixed $nomimage
     */
    public function setNomimage($nomimage): void
    {
        $this->nomimage = $nomimage;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setEvenement($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getEvenement() === $this) {
                $reservation->setEvenement(null);
            }
        }

        return $this;
    }
}

src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Il faut remplir le champs du message")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }
    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Entity/Reply.php
<?php

namespace App\Entity;

use App\Repository\ReplyRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=ReplyRepository::class)
 */
class Reply
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     *  @Assert\Length(
     *      min = 2,
     *      max = 15,
     *      minMessage = "titre Reclamation doit etre au minimum {{ limit }} characters long",
     *      maxMessage = "titre Reclamation ne doit pas passer {{ limit }} characters")
     */
    private $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datereply;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotNull
     * @Assert\Length(
     *      min = 10,
     *      max = 200,
     *      minMessage = "description doit etre au minimum {{ limit }} characters long",
     *      maxMessage = "description ne doit pas depasser {{ limit }} characters"
     * )
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Reclamation::class, inversedBy="replies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Reclamation;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="replies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDatereply(): ?\DateTimeInterface
    {
        return $this->datereply;
    }

    public function setDatereply(\DateTimeInterface $datereply): self
    {
        $this->datereply = $datereply;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReclamation(): ?Reclamation
    {
        return $this->Reclamation;
    }

    public function setReclamation(?Reclamation $Reclamation): self
    {
        $this->Reclamation = $Reclamation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\DomCrawler\Field\TextareaFormField;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;




class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('titre')
            ->add('description')
            ->add('date')
            ->add('image',FileType::class, [
                'label' => false,
                'multiple' => false,
                'mapped' => false,
                'required' => false
            ])
            ->add('time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,

        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EvenementController extends AbstractController
{
    /**
     * @Route("/evenement", name="app_evenement")
     */
    public function index(): Response
    {
        return $this->render('evenement/index.html.twig', [
            'controller_name' => 'EvenementController',
        ]);
    }
    /**
     * @param EvenementRepository $repository
     * @return Response
     * @Route ("/blog/evenements", name="events")
     */
    function Affiche( ){
        $repo=$this->getDoctrine()->getRepository(Evenement::class);

        $evenement=$repo->findAll();

        return $this->render('Frontend/evenement/index.html.twig',
            [
                'Evenement'=>$evenement,
            ]);
    }


    /**
     * @param Request $request
     * @param EvenementRepository $repository
     * @return Response
     * @Route ("/vendeur/add/{id}", name="add")
     */
    public function Add(Request $request , RestaurantRepository $repo,$id ): Response
    { $Re=$repo->find($id);
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

                $file = $form->get( 'image' )->getData();
            if($file != null) {
                //  $evenement->setRestaurant($Restaurant);;
                $uploads_directory = $this->getParameter( 'uploads_directory' );
                $filename = $evenement->getTitre() . '.' . $file->guessExtension();
                $file->move(
                    $uploads_directory,
                    $filename
                );
                // On stocke l'image dans la base de données (son nom)
                $evenement->setImage( $filename );
                $evenement->setNomimage( $filename );
            }
            $evenement->setRestaurant($Re);


            // $evenement->setCreatedAt(new \DateTime());



            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('app_vendeur');
        }

        return $this->render('Frontend/evenement/Newevent.html.twig', [
            'Evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param EvenementRepository $repository
     * @param $id
     * @param Request $request
     * @Route ("vendeur/edit/{id}",name="editE")
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */

    function Update(EvenementRepository $repository,$id,Request $request)
    {
        $evenement = $repository->find($id);
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('app_vendeur');
        }

        return $this->render('Frontend/evenement/editE.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param $id
     * @param EvenementRepository $rep

     * @Route ("/Delete/{id}", name="deleteE")
     */
    function Delete($id,EvenementRepository $rep){
        $evenement=$rep->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($evenement);
        $em->flush();
        return $this->redirectToRoute('app_vendeur');

    }
}

templates/Frontend/evenement/Newevent.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Zvenn - Quality delivery or takeaway food">
    <meta name="Zvenn" content="Zvenn">
    <title>{% block title %}ajouter event{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block stylesheets %}

        <!-- GOOGLE WEB FONT -->
        <link href="{{ asset("https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap") }}" rel="stylesheet">
        <!-- BASE CSS -->
        <link href="{{ asset("/frontoffice/css/bootstrap_customized.css/bootstrap_customized.min.css") }}" rel="stylesheet">
        <link href="{{ asset("/frontoffice/css/style.css") }}" rel="stylesheet">

        <!-- SPECIFIC CSS -->
        <link href="{{asset("/frontoffice/css/detail-page.css") }}" rel="stylesheet">

        <!-- YOUR CUSTOM CSS -->
        <link href="{{asset("/frontoffice/css/custom.css")  }}" rel="stylesheet">

    {% endblock %}

    {% block javascripts %}
        <!-- COMMON SCRIPTS -->
        <script src="{{"/frontoffice/js/common_scripts.min.js" }}"></script>
        <script src="{{ "/frontoffice/js/common_func.js" }}"></script>
        <script src="{{ "/frontoffice/assets/validate.js" }}"></script>
    {% endblock %}
</head>
{{ include('Frontend/nav2.html.twig') }}


{{ form_start(form) }}

<div class="container margin_60_20" id="submit">

    <div class="row justify-content-center">

        <div class="col-lg-5">
            <div class="text-center add_bottom_15">
                <h4>Ajouter event</h4>
                <p> Veiller remplir tout les champs </p>
                    <div class="col-md-6">

                        <div class="form-group">
                            <h6>Titre</h6>
                            {{ form_widget(form.titre,{'attr':{
                                    'placeholder':'titre','class':'titre'
                            }}) }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <h6>Description</h6>
                            {{ form_widget(form.description,{'attr':{
                                'placeholder':'description','class':'description'
                            }}) }}
                        </div>
                    </div>
                </div>
            <div class="col-md-6">

                <div class="form-group">
                    <h6>Date</h6>
                    {{ form_widget(form.date,{'attr':{
                        'placeholder':'date','class':'date'
                    }}) }}
                </div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    <h6>Image</h6>
                    {{ form_widget(form.image,{'attr':{
                        'placeholder':'image','class':'image'
                    }}) }}
                </div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    <h6>Time</h6>
                    {{ form_widget(form.time,{'attr':{
                        'placeholder':'time','class':'time'
                    }}) }}
                </div>
            </div>





                {{ form(form,{'method':'GET'}) }}
                <div class="form-group text-center">
                    <button class="btn_1 gradient">Ajouter</button>
                </div>

            </div>
        </div>
    </div>
{{ form_end(form) }}

templates/Frontend/evenement/indexback.html.twig
{% extends 'admin/index.html.twig' %}
{% block title %} Tableau{% endblock %}

    {% block main %}
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card my-4">
                    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                            <h6 class="text-white text-capitalize ps-3">tableau des restaurants</h6>
                        </div>
                    </div>
                    <div class="card-body px-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Restaurant</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">categorie</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">date ajout</th>
                                    <th class="text-secondary opacity-7"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for r in restaurant %}
                                <tr>
                                    <td>

                                        <div class="d-flex px-2 py-1">
                                            <div>
                                                <img src="{{ asset('/uploads/' ~ r.nomImage ) }}" class="avatar avatar-sm me-3 border-radius-lg" alt="user1">
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">{{ r.nomRestaurant }}</h6>
                                                <p class="text-xs text-secondary mb-0">{{ r.user.email }}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <p class="text-xs font-weight-bold mb-0">{{ r.categorieRestaurant }}</p>
                                    </td>
                                    <td class="align-middle text-center text-sm">
                                    {% if r.status=="verified" %}
                                        <span class="badge badge-sm bg-gradient-success">verified</span>
                                        {% else %}
                                        <span class="badge badge-sm bg-gradient-danger">archived</span>
                                        {% endif %}
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-secondary text-xs font-weight-bold">{{ r.createdAt|date('d/m/y h:m:s')}} </span>
                                    </td>
                                    <td class="align-middle">
                                    {% if r.status == 'not verified' %}
                                        <a href="{{ path ('updatearchive',{'id':r.id}) }}" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                            verifier
                                        </a>
                                        {% else %}
                                        <a href="{{ path ('updatearchive',{'id':r.id}) }}" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                            archiver
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}





                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card my-4">
                    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                            <h6 class="text-white text-capitalize ps-3">Produits</h6>
                        </div>
                    </div>
                    <div class="card-body px-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center justify-content-center mb-0">
                                <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Image</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Nom</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Restaurant</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder  opacity-7 ps-2">Prix</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder  opacity-7 ps-2">Date Ajout</th>

                                </tr>
                                </thead>

                                <tbody>
                                    {% for p in prod.getProduits %}
                                <tr>
                                    <td>
                                        <div class="d-flex px-2">
                                            <div>
                                                <img src="{{ asset('/uploads/' ~ p.nomimageProduit ) }}" class="avatar avatar-sm rounded-circle me-2" alt="spotify">
                                            </div>
                                            <div class="my-auto">
                                                <h6 class="mb-0 text-sm"></h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="text-sm font-weight-bold mb-0">{{ p.nomProduit }}</span>
                                    </td>
                                    <td>
                                        <span class="text-xs font-weight-bold">{{p.restaurant.nomRestaurant}}</span>
                                    </td>
                                    <td>
                                        <span class="text-sm font-weight-bold mb-0">{{ p.prixProduit }} dt</span>
                                    </td>
                                    <td>
                                        <span class="text-xs font-weight-bold">{{ p.createdAt|date('d/m/y h:m:s')}}</span>
                                    </td>

                                </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

    {% block body %}
<div class="fixed-plugin">
    <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
        <i class="material-icons py-2">settings</i>
    </a>
    <div class="card shadow-lg">
        <div class="card-header pb-0 pt-3">
            <div class="float-start">
                <h5 class="mt-3 mb-0">Material UI Configurator</h5>
                <p>See our dashboard options.</p>
            </div>
            <div class="float-end mt-4">
                <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
                    <i class="material-icons">clear</i>
                </button>
            </div>
            <!-- End Toggle Button -->
        </div>
        <hr class="horizontal dark my-1">
        <div class="card-body pt-sm-3 pt-0">
            <!-- Sidebar Backgrounds -->
            <div>
                <h6 class="mb-0">Sidebar Colors</h6>
            </div>
            <a href="javascript:void(0)" class="switch-trigger background-color">
                <div class="badge-colors my-2 text-start">
                    <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                    <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                    <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                    <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                    <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                    <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
                </div>
            </a>
            <!-- Sidenav Type -->
            <div class="mt-3">
                <h6 class="mb-0">Sidenav Type</h6>
                <p class="text-sm">Choose between 2 different sidenav types.</p>
            </div>
            <div class="d-flex">
                <button class="btn bg-gradient-dark px-3 mb-2 active" data-class="bg-gradient-dark" onclick="sidebarType(this)">Dark</button>
                <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
                <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
            </div>
            <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
            <!-- Navbar Fixed -->
            <div class="mt-3 d-flex">
                <h6 class="mb-0">Navbar Fixed</h6>
                <div class="form-check form-switch ps-0 ms-auto my-auto">
                    <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
                </div>
            </div>
            <hr class="horizontal dark my-3">
            <div class="mt-2 d-flex">
                <h6 class="mb-0">Light / Dark</h6>
                <div class="form-check form-switch ps-0 ms-auto my-auto">
                    <input class="form-check-input mt-1 ms-auto" type="checkbox" id="dark-version" onclick="darkMode(this)">
                </div>
            </div>
            <hr class="horizontal dark my-sm-4">
            <a class="btn btn-outline-dark w-100" href="">View documentation</a>
            <div class="w-100 text-center">
                <a class="github-button" href="https://github.com/creativetimofficial/material-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/material-dashboard on GitHub">Star</a>
                <h6 class="mt-3">Thank you for sharing!</h6>
                <a href="https://twitter.com/intent/tweet?text=Check%20Material%20UI%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fsoft-ui-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
                    <i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
                </a>
                <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.creative-tim.com/product/material-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
                    <i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
<script src="{{ asset('backoffice/assets/js/core/popper.min.js') }}"></script>
<script src="{{ asset('backoffice/assets/js/core/bootstrap.min.js') }}"></script>
<script src="{{ asset('backoffice/assets/js/plugins/perfect-scrollbar.min.js') }}"></script>>
<script src="{{ asset('backoffice/assets/js/plugins/smooth-scrollbar.min.js') }}"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="{{ absolute_url('https://buttons.github.io/buttons.js') }}"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{ asset('backoffice/assets/js/material-dashboard.min.js?v=3.0.0') }}"></script>
{% endblock %}